// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.29.3
// source: internal/client/grpc/proto/gate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticker string `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
}

func (x *OpenOrderRequest) Reset() {
	*x = OpenOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_client_grpc_proto_gate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrderRequest) ProtoMessage() {}

func (x *OpenOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_grpc_proto_gate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrderRequest.ProtoReflect.Descriptor instead.
func (*OpenOrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_grpc_proto_gate_proto_rawDescGZIP(), []int{0}
}

func (x *OpenOrderRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type OpenOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *OpenOrderResponse) Reset() {
	*x = OpenOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_client_grpc_proto_gate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrderResponse) ProtoMessage() {}

func (x *OpenOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_grpc_proto_gate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrderResponse.ProtoReflect.Descriptor instead.
func (*OpenOrderResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_grpc_proto_gate_proto_rawDescGZIP(), []int{1}
}

func (x *OpenOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OpenOrderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_client_grpc_proto_gate_proto protoreflect.FileDescriptor

var file_internal_client_grpc_proto_gate_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x74, 0x65, 0x22, 0x2a, 0x0a,
	0x10, 0x4f, 0x70, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x43, 0x0a, 0x11, 0x4f, 0x70, 0x65,
	0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x4d,
	0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a,
	0x09, 0x4f, 0x70, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x67, 0x61, 0x74,
	0x65, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1c, 0x5a,
	0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_client_grpc_proto_gate_proto_rawDescOnce sync.Once
	file_internal_client_grpc_proto_gate_proto_rawDescData = file_internal_client_grpc_proto_gate_proto_rawDesc
)

func file_internal_client_grpc_proto_gate_proto_rawDescGZIP() []byte {
	file_internal_client_grpc_proto_gate_proto_rawDescOnce.Do(func() {
		file_internal_client_grpc_proto_gate_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_client_grpc_proto_gate_proto_rawDescData)
	})
	return file_internal_client_grpc_proto_gate_proto_rawDescData
}

var file_internal_client_grpc_proto_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_client_grpc_proto_gate_proto_goTypes = []interface{}{
	(*OpenOrderRequest)(nil),  // 0: gate.OpenOrderRequest
	(*OpenOrderResponse)(nil), // 1: gate.OpenOrderResponse
}
var file_internal_client_grpc_proto_gate_proto_depIdxs = []int32{
	0, // 0: gate.GateService.OpenOrder:input_type -> gate.OpenOrderRequest
	1, // 1: gate.GateService.OpenOrder:output_type -> gate.OpenOrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_client_grpc_proto_gate_proto_init() }
func file_internal_client_grpc_proto_gate_proto_init() {
	if File_internal_client_grpc_proto_gate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_client_grpc_proto_gate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_client_grpc_proto_gate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_client_grpc_proto_gate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_client_grpc_proto_gate_proto_goTypes,
		DependencyIndexes: file_internal_client_grpc_proto_gate_proto_depIdxs,
		MessageInfos:      file_internal_client_grpc_proto_gate_proto_msgTypes,
	}.Build()
	File_internal_client_grpc_proto_gate_proto = out.File
	file_internal_client_grpc_proto_gate_proto_rawDesc = nil
	file_internal_client_grpc_proto_gate_proto_goTypes = nil
	file_internal_client_grpc_proto_gate_proto_depIdxs = nil
}
